### ISSUE TITLE
tclap and --qic

### ISSUE THREAD

**Issue by fabi-mobile** [algomaus/QuartetScores#5]
HI,

Just want to let you know that tclap is not available. 

Also the --qic flag is unrecognised in the version available in the release tab.

Thanks for the program

**Comment by lutteropp** [comment]
Hi,

tclap is included as a submodule in git. Did you clone with `--recurse-submodules`? Alternatively, if you already cloned the repository, you need to run `git submodule init` and then `git submodule update` within the repository.
See here for further information on submodules: https://git-scm.com/book/en/v2/Git-Tools-Submodules

The `--qic` flag was indeed not yet included in the release, but it is available in the newest version from the repository (in the master branch). This is because somebody only recently asked me to provide an option to just compute and print the qic scores... Thanks for pointing this out, I will make a newer release in the repo.

**Comment by fabi-mobile** [comment]
Thank you! Really appreciate your response and time

**Comment by lutteropp** [comment]
Oh... now I see the issue! Looks like the tclap git repository has been deleted in the meanwhile... stupid submodules... fixing the dependency now, luckily there seem to exist some mirror repositories on GitHub.

**Comment by lutteropp** [comment]
I fixed the links to tclap now. Please try pulling the newest version.

**Comment by fabi-mobile** [comment]
Thank you. It downloads and compiles now
